version: '3.8'
services:
  db_postgres:
    image: postgres:12.9-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
  
  db_mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_DATABASE: books
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017